apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hrmanager.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hrmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
